version: "3.8"

services:
  database:
    image: mongo
    container_name: "mongodb"
    environment: 
        MONGO_INITDB_DATABASE: proy1
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
        - ~/mongo/db-data:/data/db
    ports:
        - "27017:27017"